apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exec-operator
  template:
    metadata:
      labels:
        name: exec-operator
    spec:
      serviceAccountName: exec-operator
      containers:
        - name: exec-operator
          # Replace this with the built image name
          image: exec-service
          command:
          - exec-operator
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "exec-operator"
